//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace logbook
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_main
    {
        public int id { get; set; }
        public string phrase { get; set; }
        public string feeling { get; set; }
        public System.DateTime feeling_date { get; set; }
    }
}
